name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - release/*
      - main

  pull_request:
    branches:
      - develop
      - release/*
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        options:
          - dev
          - staging
          - production

      feature_flag:
        description: 'Feature flag to deploy to'
        required: false
        default: 'false'
        type: boolean

      deploy_to_prod:
        description: 'Deploy to production'
        required: false
        default: 'false'
        type: boolean

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  apex_test:
    runs-on: ubuntu-latest
    needs: build_and_lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test Coverage Check
        run: |
          TEST_COVERAGE=$(sfdx force:apex:test:report --codecoverage --json | jq -r '.result.summary.testRunCoverage')
          if (( $(echo "$TEST_COVERAGE < 75" | bc -l) )); then
            echo "Test coverage below 75%, failing job."
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: apex_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Select Deployment Environment
        run: |
          echo "Authenticating to target environment..."
          if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            sfdx force:auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile assets/server.key --username ${{ secrets.SF_PRODUCTION_USERNAME }} --instanceurl https://login.salesforce.com
          elif [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            sfdx force:auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile assets/server.key --username ${{ secrets.SF_STAGING_USERNAME }} --instanceurl https://test.salesforce.com
          else
            sfdx force:auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile assets/server.key --username ${{ secrets.SF_DEV_USERNAME }} --instanceurl https://login.salesforce.com
          fi

      - name: Deploy Source to Target Environment
        run: |
          echo "Deploying to the target environment..."
          sfdx force:source:deploy -p force-app --testlevel RunLocalTests

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event.inputs.deploy_to_prod == 'true'
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to Production environment..."
          sfdx force:source:deploy -p force-app --testlevel RunAllTestsInOrg

  feature_flag:
    runs-on: ubuntu-latest
    if: github.event.inputs.feature_flag == 'true'
    steps:
      - name: Feature Flag Action
        run: echo "Feature flag is enabled, performing special tasks..."
